### ISSUE TITLE
Broken on Plasma 5.25 - can't recompile

### ISSUE THREAD

**Issue by michaldybczak** [zzag/kwin-effects-yet-another-magic-lamp#59]
I learned that after some effects, the effect isn't working, and I need to recompile the plugin and restart kwin. This time this didn't work, because of the compilation error.

```
[ 10%] Built target kwin_yetanothermagiclamp_config_autogen
[ 26%] Generating YetAnotherMagicLampConfig.h, YetAnotherMagicLampConfig.cpp
[ 26%] Generating ui_YetAnotherMagicLampEffectKCM.h
[ 26%] Generating kwineffects_interface.cpp, kwineffects_interface.h
[ 26%] Built target kwin4_effect_yetanothermagiclamp_autogen
[ 31%] Generating YetAnotherMagicLampConfig.h, YetAnotherMagicLampConfig.cpp
[ 36%] Generating kwineffects_interface.moc
[ 68%] Building CXX object src/kcm/CMakeFiles/kwin_yetanothermagiclamp_config.dir/plugin.cc.o
[ 68%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/Model.cc.o
[ 68%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/kwin4_effect_yetanothermagiclamp_autogen/mocs_compilation.cpp.o
[ 68%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/YetAnotherMagicLampEffect.cc.o
[ 68%] Building CXX object src/kcm/CMakeFiles/kwin_yetanothermagiclamp_config.dir/kwin_yetanothermagiclamp_config_autogen/mocs_compilation.cpp.o
[ 68%] Building CXX object src/kcm/CMakeFiles/kwin_yetanothermagiclamp_config.dir/YetAnotherMagicLampEffectKCM.cc.o
[ 73%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/plugin.cc.o
[ 78%] Building CXX object src/kcm/CMakeFiles/kwin_yetanothermagiclamp_config.dir/YetAnotherMagicLampConfig.cpp.o
[ 84%] Building CXX object src/kcm/CMakeFiles/kwin_yetanothermagiclamp_config.dir/kwineffects_interface.cpp.o
/mnt/home-hdd/build/kwin-effects-yet-another-magic-lamp/src/kwin-effects-yet-another-magic-lamp-5.24.0/src/Model.cc: In member function ‘void Model::step(std::chrono::milliseconds)’:
/mnt/home-hdd/build/kwin-effects-yet-another-magic-lamp/src/kwin-effects-yet-another-magic-lamp-5.24.0/src/Model.cc:183:16: error: ‘class KWin::TimeLine’ has no member named ‘update’
  183 |     m_timeLine.update(delta);
      |                ^~~~~~
[ 89%] Building CXX object src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/YetAnotherMagicLampConfig.cpp.o
/mnt/home-hdd/build/kwin-effects-yet-another-magic-lamp/src/kwin-effects-yet-another-magic-lamp-5.24.0/src/YetAnotherMagicLampEffect.cc: In member function ‘virtual void YetAnotherMagicLampEffect::prePaintWindow(KWin::EffectWindow*, KWin::WindowPrePaintData&, std::chrono::milliseconds)’:
/mnt/home-hdd/build/kwin-effects-yet-another-magic-lamp/src/kwin-effects-yet-another-magic-lamp-5.24.0/src/YetAnotherMagicLampEffect.cc:165:12: error: ‘class KWin::EffectWindow’ has no member named ‘enablePainting’
  165 |         w->enablePainting(KWin::EffectWindow::PAINT_DISABLED_BY_MINIMIZE);
      |            ^~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/build.make:99: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/Model.cc.o] Błąd 1
make[2]: *** Oczekiwanie na niezakończone zadania....
make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/build.make:113: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/YetAnotherMagicLampEffect.cc.o] Błąd 1
[ 94%] Linking CXX shared module ../../bin/kwin_yetanothermagiclamp_config.so
make[1]: *** [CMakeFiles/Makefile2:360: src/CMakeFiles/kwin4_effect_yetanothermagiclamp.dir/all] Błąd 2
make[1]: *** Oczekiwanie na niezakończone zadania....
[ 94%] Built target kwin_yetanothermagiclamp_config
make: *** [Makefile:146: all] Błąd 2
==> ERROR: There is error in build().
    Aborting...
```

**Comment by Curve** [comment]
Fixed by #58

**Comment by michaldybczak** [comment]
I checked, and it still throws error, although I cleaned the build cache. Maybe the AUR's PKGBUILD is still downloading the old version from github? Is there any new release version to update in PKGBUILD to download the version with the fix?

**Comment by Curve** [comment]
> I checked, and it still throws error, although I cleaned the build cache. Maybe the AUR's PKGBUILD is still downloading the old version from github? Is there any new release version to update in PKGBUILD to download the version with the fix?

Make sure to just use the git package

But yes you could also edit the pkgbuild to change the ref

**Comment by michaldybczak** [comment]
I changed PKGBUILD to 5.25 and used SKIP for veryfication, the right release downloaded, builded successfully. I enabled the effect and it works, so I can confirm that the fix is working. Only AUR package should get updated PKGBUILD and it will be fine.

Thanks! Closing the topic :).
